# Changes here will be overwritten by Copier
Authors: Antonios Gementzopoulos
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Antonios Gementzopoulos
PackageName: UniformStreamlines
PackageOwner: antoniosgeme
PackageUUID: d45a1faf-ed48-5bcd-af90-6f9b3352014e
StrategyConfirmIncluded: false
StrategyLevel: 1
StrategyReviewExcluded: false
_src_path: /Users/antoniosgementzopoulos/.julia/packages/BestieTemplate/fOzc4
